# Generated by Django 5.1.1 on 2024-09-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('born', models.IntegerField()),
                ('nation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'ordering': ['player']},
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='age',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='born',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='position',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='squad',
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='base.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='base.team'),
        ),
    ]
