# Generated by Django 5.1.1 on 2024-09-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_player_slug_playerstats_slug_team_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerStats',
            new_name='PlayerStat',
        ),
    ]
