# Generated by Django 4.1 on 2024-09-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_playerstats_playerstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='player',
            field=models.OneToOneField(help_text='Player associated with this player stat.', on_delete=django.db.models.deletion.CASCADE, related_name='playerstats', to='base.player'),
        ),
    ]
