# Generated by Django 4.1 on 2024-09-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_playerstat_player'),
        ('base', '0005_remove_playerstat_slug'),
    ]

    operations = [
    ]
