# Generated by Django 4.1 on 2024-09-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_merge_20240914_0520"),
    ]

    operations = [migrations.RenameModel("Team", "Club")]
