# Generated by Django 4.1 on 2024-09-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_auto_20240927_2249"),
    ]

    operations = [
        migrations.RenameField("Player", "team", "club"),
    ]
