# Generated by Django 4.1 on 2024-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_club_avg_age_club_club_code_club_elo_club_squad_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='other_names',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
